name: Update browserslist

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

concurrency:
  group: update-browserslist

jobs:
  update-browserslist:

    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: "-Dorg.gradle.caching=false -Dorg.gradle.daemon=false"
      DEFAULT_NODE_VERSION: "16"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
          check-latest: true

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # See https://github.com/browserslist/browserslist#browsers-data-updating
      - name: Run browserslist update
        run: ./.github/workflows/browserslist.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
