name: Update browserslist

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

concurrency:
  group: update-browserslist

jobs:
  update-browserslist:

    runs-on: ubuntu-latest

    env:
      DEFAULT_NODE_VERSION: "20"

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
          check-latest: true

      # See https://github.com/browserslist/browserslist#browsers-data-updating
      - name: Run browserslist update
        run: ./.github/workflows/browserslist.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
