name: Update browserslist

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: { }

env:
  NODE_VERSION: "22"

concurrency:
  group: update-browserslist

jobs:
  update-browserslist:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true

      # See https://github.com/browserslist/browserslist#browsers-data-updating
      - name: Run browserslist update
        run: ./.github/workflows/browserslist.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
