name: Build

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java:
          - "11"
          - "15"

      fail-fast: true

    env:
      GRADLE_OPTS: "-Dorg.gradle.caching=false -Dorg.gradle.daemon=false"
      DOCKER_USERNAME: pgentile
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
      - name: About env
        run: |
          echo "Env"
          env | sort
          echo
          echo "Github Action vars"
          echo "github.ref = ${{ github.ref  }}"
          echo "matrix.java = ${{ matrix.java }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cypress cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CYPRESS_CACHE_FOLDER }}
          key: ${{ runner.os }}-cypress-${{ hashFiles('zucchini-ui-e2e-tests/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Check Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Install JS dependencies
        run: ./gradlew yarnInstall

      - name: Assemble project
        run: ./gradlew assemble

      - name: Test and check project
        run: ./gradlew check

      - name: Build Docker image
        run: ./gradlew dockerBuild

      - name: Start server with Docker
        run: ./gradlew dockerComposeUp

      - name: Run Cypress tests
        working-directory: ./zucchini-ui-e2e-tests
        run: yarn test

      - name: Collect Cypress videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: Cypress videos for Java ${{ matrix.java }}
          path: ./zucchini-ui-e2e-tests/cypress/videos

      - name: Push Docker image
        if: github.ref == 'refs/heads/master' && matrix.java == '11'
        run: |
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          ./gradlew dockerPush
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
